require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.lsp"
require "user.settings.cmp"
require "user.settings.telescope"
require "user.settings.harpoon"
